---
- name: Include pre-validation tasks
  ansible.builtin.include_tasks:
    file: pre-validate.yml
    apply:
      tags:
        - always
  tags:
    - always

- name: Openshift deployment tasks
  block:
    - name: Include OpenShift initialization tasks
      ansible.builtin.include_tasks:
        file: initialization.yml
        apply:
          tags:
            - always
      tags:
        - always

    - name: Include Ansible Automation Platform operator install tasks
      when:
        - aap_ocp_install_operator is defined
      ansible.builtin.include_tasks:
        file: install-operator.yml
        apply:
          tags:
            - operator
      tags:
        - operator

    - name: Include Ansible Automation Platform platform install tasks
      when:
        - aap_ocp_install_platform is defined
        - __aap_ocp_install_25_install | bool
      ansible.builtin.include_tasks:
        file: install-platform.yml
        apply:
          tags:
            - platform
      tags:
        - platform

    - name: Include Ansible Automation Platform controller install tasks
      when:
        - aap_ocp_install_controller is defined
        - not __aap_ocp_install_25_install | bool
      ansible.builtin.include_tasks:
        file: install-controller.yml
        apply:
          tags:
            - controller
      tags:
        - controller

    - name: Include Ansible Automation Platform hub install tasks
      when:
        - aap_ocp_install_hub is defined
        - not __aap_ocp_install_25_install | bool
      ansible.builtin.include_tasks:
        file: install-hub.yml
        apply:
          tags:
            - hub
      tags:
        - hub

    - name: Include Ansible Automation Platform EDA install tasks
      when:
        - aap_ocp_install_eda is defined
        - not __aap_ocp_install_25_install | bool
      ansible.builtin.include_tasks:
        file: install-eda.yml
        apply:
          tags:
            - eda
      tags:
        - eda

  always:
    - name: Include OpenShift finalization tasks
      ansible.builtin.include_tasks:
        file: finalization.yml
        apply:
          tags:
            - always
      tags:
        - always
...
