---
- name: pre-validate-platform | Ensure platform instance name variable is set (block)
  block:
    - name: pre-validate-platform | Ensure platform instance name variable is set
      ansible.builtin.assert:
        that:
          - aap_ocp_install_platform['instance_name'] | default('', true) | length > 0
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - platform instance_name
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_platform['instance_name'] must be set"] }}

- name: pre-validate-platform | Ensure controller admin username variable is set (block)
  when:
    - aap_ocp_install_controller['admin_user'] is defined
  block:
    - name: pre-validate-platform | Ensure controller admin username variable is set
      ansible.builtin.assert:
        that:
          - aap_ocp_install_controller['admin_user'] | default('', true) | length > 0
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - controller admin_user
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_controller['admin_user'] must be a non-empty string"] }}

- name: pre-validate-platform | Ensure platform namespace variable is valid if set (block)
  when:
    - aap_ocp_install_platform['namespace'] is defined
  block:
    - name: pre-validate-platform | Ensure platform namespace variable is valid
      ansible.builtin.assert:
        that:
          - aap_ocp_install_platform['namespace'] | default("", true) is match('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - namespace
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_platform['namespace'] must be a lowercase RFC 1123 label consisting of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'"] }}

- name: pre-validate-platform | Ensure platform link text variable is valid if set (block)
  when:
    - aap_ocp_install_platform['link_text'] is defined
  block:
    - name: pre-validate-platform | Ensure platform link text variable is set
      ansible.builtin.assert:
        that:
          - aap_ocp_install_platform['link_text'] | default('', true) | length > 0
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - platform link_text
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_platform['link_text'] must be a non-empty string"] }}

- name: pre-validate-platform | Ensure controller image pull policy is valid (block)
  when:
    - aap_ocp_install_controller['image_pull_policy'] is defined
  block:
    - name: pre-validate-platform | Ensure controller image pull policy is valid
      ansible.builtin.assert:
        that:
          - aap_ocp_install_controller['image_pull_policy'] is in ['IfNotPresent', 'Always', 'Never']
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - controller image_pull_policy
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_controller['image_pull_policy'] must be one of: IfNotPresent, Always, or Never"] }}

- name: pre-validate-platform | Ensure controller create preload data is valid (block)
  when:
    - aap_ocp_install_controller['create_preload_data'] is defined
  block:
    - name: pre-validate-platform | Ensure controller create preload data is valid
      ansible.builtin.assert:
        that:
          - (aap_ocp_install_controller['create_preload_data'] | string | lower) is in ['true', 'false']
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - controller create_preload_data
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_controller['create_preload_data'] must be one of: true or false"] }}

- name: pre-validate-platform | Ensure controller garbage collect secrets is valid (block)
  when:
    - aap_ocp_install_controller['garbage_collect_secrets'] is defined
  block:
    - name: pre-validate-platform | Ensure controller garbage collect secrets is valid
      ansible.builtin.assert:
        that:
          - (aap_ocp_install_controller['garbage_collect_secrets'] | string | lower) is in ['true', 'false']
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - controller garbage_collect_secrets
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_controller['garbage_collect_secrets'] must be one of: true or false"] }}

- name: pre-validate-platform | Ensure controller projects persistence is valid (block)
  when:
    - aap_ocp_install_controller['projects_persistence'] is defined
  block:
    - name: pre-validate-platform | Ensure controller projects persistence is valid
      ansible.builtin.assert:
        that:
          - (aap_ocp_install_controller['projects_persistence'] | string | lower) is in ['true', 'false']
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - controller projects_persistence
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_controller['projects_persistence'] must be one of: true or false"] }}

- name: pre-validate-platform | Ensure controller replicas is valid (block)
  when:
    - aap_ocp_install_controller['replicas'] is defined
  block:
    - name: pre-validate-platform | Ensure controller replicas is valid
      ansible.builtin.assert:
        that:
          - (aap_ocp_install_controller['replicas'] | int) > 0
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - controller replicas
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_controller['replicas'] must be a number greater than 0"] }}

- name: pre-validate-platform | Ensure controller projects storage size is valid (block)
  when:
    - aap_ocp_install_controller['projects_storage_size'] is defined
  block:
    - name: pre-validate-platform | Ensure controller projects storage size is valid
      ansible.builtin.assert:
        that:
          - (aap_ocp_install_controller['projects_storage_size'] | regex_replace('^(?P<size>[0-9]+)(?P<si>Ki|K|Mi|M|Gi|G|Ti|T|Pi|P|Ei|E)$', '\\g<size>') | int) > 0
          - (aap_ocp_install_controller['projects_storage_size'] | regex_replace('^(?P<size>[0-9]+)(?P<si>Ki|K|Mi|M|Gi|G|Ti|T|Pi|P|Ei|E)$', '\\g<si>')) is in ['Ki','K','Mi','M','Gi','G','Ti','T','Pi','P','Ei','E']
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - projects_storage_size replicas
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_controller['projects_storage_size'] must be a number greater than 0 with a size (e.g. 12Gi or 10000M)"] }}

- name: pre-validate-platform | Ensure hub storage type is valid (block)
  when:
    - aap_ocp_install_hub is defined
    - aap_ocp_install_hub['storage_type'] is defined
  block:
    - name: pre-validate-platform | Ensure hub storage type is valid
      ansible.builtin.assert:
        that:
          - (aap_ocp_install_hub['storage_type']) is in ['file', 'S3', 'azure']
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - storage_type
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_hub['storage_type'] must be 'file', 'S3' or 'azure'"] }}

- name: pre-validate-platform | Ensure hub file storage settings are valid (block)
  when:
    - aap_ocp_install_hub['storage_type'] is defined
    - aap_ocp_install_hub['storage_type'] == 'file'
  block:
    - name: pre-validate-platform | Ensure hub file storage settings are valid
      ansible.builtin.assert:
        that:
          - (aap_ocp_install_hub['file_storage_size'] is not defined) or (aap_ocp_install_hub['file_storage_size'] | regex_replace('^(?P<size>[0-9]+)(?P<si>Ki|K|Mi|M|Gi|G|Ti|T|Pi|P|Ei|E)$', '\\g<size>') | int) > 0
          - (aap_ocp_install_hub['file_storage_size'] is not defined) or (aap_ocp_install_hub['file_storage_size'] | regex_replace('^(?P<size>[0-9]+)(?P<si>Ki|K|Mi|M|Gi|G|Ti|T|Pi|P|Ei|E)$', '\\g<si>')) is in ['Ki','K','Mi','M','Gi','G','Ti','T','Pi','P','Ei','E']
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - file storage_type
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_hub['file_storage_size'] must be a number greater than 0 with a size (e.g. 12Gi or 10000M)"] }}

- name: pre-validate-platform | Ensure hub S3 storage settings are valid (block)
  when:
    - aap_ocp_install_hub['storage_type'] is defined
    - aap_ocp_install_hub['storage_type'] == 'S3'
  block:
    - name: pre-validate-platform | Ensure hub S3 storage settings are valid
      ansible.builtin.assert:
        that:
          - (aap_ocp_install_hub['object_storage_s3_secret']) is defined
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - S3 secret
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_hub['object_storage_s3_secret'] must be the name of a valid S3 storage secret name"] }}

- name: pre-validate-platform | Ensure hub Azure storage settings are valid (block)
  when:
    - aap_ocp_install_hub['storage_type'] is defined
    - aap_ocp_install_hub['storage_type'] == 'azure'
  block:
    - name: pre-validate-platform | Ensure hub Azure storage settings are valid
      ansible.builtin.assert:
        that:
          - (aap_ocp_install_hub['object_storage_azure_secret']) is defined
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - Azure secret
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_hub['object_storage_azure_secret'] must be the name of a valid Azure storage secret name"] }}

- name: pre-validate-platform | Ensure platform namespace manifest overrides are a mapping when set (block)
  when: aap_ocp_install_platform['namespace_manifest_overrides'] is defined
  block:
    - name: pre-validate-platform | Ensure platform namespace manifest overrides are a mapping when set
      ansible.builtin.assert:
        that:
          - aap_ocp_install_platform['namespace_manifest_overrides'] is mapping
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - platform namespace_manifest_overrides
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_platform['namespace_manifest_overrides'] must be a mapping (dictionary)"] }}

- name: pre-validate-platform | Ensure platform manifest overrides are a mapping when set (block)
  when: aap_ocp_install_platform['platform_manifest_overrides'] is defined
  block:
    - name: pre-validate-platform | Ensure platform manifest overrides are a mapping when set
      ansible.builtin.assert:
        that:
          - aap_ocp_install_platform['platform_manifest_overrides'] is mapping
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - platform_manifest_overrides
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_platform['platform_manifest_overrides'] must be a mapping (dictionary)"] }}

- name: pre-validate-platform | Ensure platform console link manifest overrides are a mapping when set (block)
  when: aap_ocp_install_platform['consolelink_manifest_overrides'] is defined
  block:
    - name: pre-validate-platform | Ensure platform console link manifest overrides are a mapping when set
      ansible.builtin.assert:
        that:
          - aap_ocp_install_platform['consolelink_manifest_overrides'] is mapping
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - platform consolelink_manifest_overrides
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_platform['consolelink_manifest_overrides'] must be a mapping (dictionary)"] }}

- name: pre-validate-platform | Ensure controller manifest overrides are a mapping when set (block)
  when:
    - aap_ocp_install_controller is defined
    - aap_ocp_install_controller['controller_manifest_overrides'] is defined
  block:
    - name: pre-validate-platform | Ensure controller manifest overrides are a mapping when set
      ansible.builtin.assert:
        that:
          - aap_ocp_install_controller['controller_manifest_overrides'] is mapping
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - controller_manifest_overrides
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_controller['controller_manifest_overrides'] must be a mapping (dictionary)"] }}

- name: pre-validate-platform | Ensure hub manifest overrides are a mapping when set (block)
  when:
    - aap_ocp_install_hub is defined
    - aap_ocp_install_hub['hub_manifest_overrides'] is defined
  block:
    - name: pre-validate-platform | Ensure hub manifest overrides are a mapping when set
      ansible.builtin.assert:
        that:
          - aap_ocp_install_hub['hub_manifest_overrides'] is mapping
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - hub_manifest_overrides
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_hub['hub_manifest_overrides'] must be a mapping (dictionary)"] }}

- name: pre-validate-platform | Ensure EDA manifest overrides are a mapping when set (block)
  when:
    - aap_ocp_install_eda is defined
    - aap_ocp_install_eda['eda_manifest_overrides'] is defined
  block:
    - name: pre-validate-platform | Ensure EDA manifest overrides are a mapping when set
      ansible.builtin.assert:
        that:
          - aap_ocp_install_eda['eda_manifest_overrides'] is mapping
        quiet: true
  rescue:
    - name: pre-validate-platform | Update validation errors fact - eda_manifest_overrides
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_eda['eda_manifest_overrides'] must be a mapping (dictionary)"] }}
...
