---
- name: Ensure eda instance name variable is set (block)
  block:
    - name: Ensure eda instance name variable is set
      ansible.builtin.assert:
        that:
          - aap_ocp_install_eda['instance_name'] | default('', true) | length > 0
        quiet: true
  rescue:
    - name: Update validation errors fact - eda instance_name
      ansible.builtin.set_fact:
        __aap_ocp_install_prevalidate_errors: >
          {{ __aap_ocp_install_prevalidate_errors + ["aap_ocp_install_eda['instance_name'] must be set"] }}
...
