---
- name: validate-connection | Validate OpenShift API key
  no_log: true
  ansible.builtin.uri:
    url: "{{  __aap_ocp_install_auth_results['openshift_auth']['host'] }}/version"
    method: GET
    validate_certs: "{{ aap_ocp_install_connection['validate_certs'] | default(omit) }}"
    headers:
      Authorization: Bearer {{ __aap_ocp_install_auth_results['openshift_auth']['api_key'] }}

...
