---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.2
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/djdanielsson/ansible-content-prek-actions
    rev: v26.7.2
    hooks:
      - id: ansible-lint
      - id: changelog
      - id: galaxy-importer
      - id: sanity
...
