---
extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length: disable
  colons: disable
  indentation:
    level: warning
    # Require indentation https://redhat-cop.github.io/automation-good-practices/#_yaml_and_jinja2_syntax
    indent-sequences: true
  truthy:
    level: error
    # Allow only YAML 1.2 booleans https://redhat-cop.github.io/automation-good-practices/#_yaml_and_jinja2_syntax
    allowed-values:
      - 'true'
      - 'false'
  # Enabling yamllint check based on PR #35
  document-end: enable
...
