---
namespace: infra
name: aap_utilities
version: 2.3.0-devel
description: A collection of utility roles for usage with Ansible Automation Platform
readme: README.md
authors:
    - Adebisi Oyawale @aoyawale
    - Kedar Kulkarni @kedark3
    - Tom Page @Tompage1994
    - Sean Sullivan @sean-m-sullivan
    - Eric Lavarde @ericzolf
    - Brant Evans @branic
    - Christopher Renwick @crenwick93
repository: https://github.com/redhat-cop/aap_utilities/
issues: https://github.com/redhat-cop/aap_utilities//issues
build_ignore:
    - galaxy.yml.j2
    - .github
    - .markdownlint.yml
    - .ansible-lint
    - .yamllint.yml
    - .pre-commit-config.yaml
    - .gitignore
    - .gitattributes
    - '*.tar.gz'
license:
    - GPL-3.0-or-later
tags:
    - ansible_automation_platform
    - aap
    - aap_utils
    - aap_utilities
    - collection
    - utilities
    - utils
    - tower
    - tower_utilities
    - tower_utils
    - infrastructure
dependencies:
    "ansible.posix": ">=1.0.0"
    "kubernetes.core": ">=2.2.0"
...
