# The exclude_paths does not appear to be working in pre-commit
# this issue describes similar behavior but suggested fix doesn't work
# https://github.com/ansible/ansible-lint/issues/371
#exclude_paths:
#  - roles/master_role_example/
parseable: true
use_default_rules: true
#https://github.com/ansible/ansible-lint/issues/808
# with verbosity set to 1, its dumping 'unknown file type messages'
#verbosity: 1
skip_list:
  # [E204]: "Lines should be no longer than 160 chars"
  # (Disabled in June 2020)
  - '204'
  # [E106]: "Role name {} does not match ^[a-z][a-z0-9_]+$ pattern" Issue with galaxy.yml file being variable based.
  # (Disabled in Oct 2020)
  - '106'
  # [E208]: "File permissions not mentioned. Issue created to fix"
  # (Disabled in Oct 2020)
  - '208'
...
