---
- name: release collection
  hosts: localhost
  gather_facts: False
  connection: local
  vars:
    collection_namespace: "{{ namespace  | lower | regex_replace('-','_') }}"
    collection_name: aap_utilities
    collection_version: "{{ github_tag | regex_search('(\\d.\\d.\\d.*)') }}"
    collection_repo:  undef
    api_key: undef
    repo_base_dir: "{{ playbook_dir }}/../.."

  tasks:
    - name: create galaxy.yml
      template:
        src: "{{ repo_base_dir }}/galaxy.yml.j2"
        dest: "{{ repo_base_dir }}/galaxy.yml"
        mode: '0644'

    - name: build collection
      command:
        cmd: ansible-galaxy collection build
        chdir: "{{ repo_base_dir }}"
        creates: "{{ repo_base_dir }}/{{ collection_namespace }}-{{ collection_name }}-{{ collection_version }}.tar.gz"
      register: build_result
      changed_when: "build_result.rc != 2"
      tags: build

    - name: install collection
      command:
        cmd: "ansible-galaxy collection install {{ collection_namespace }}-{{ collection_name }}-{{ collection_version }}.tar.gz -p ~/.ansible/collections/"
        chdir: "{{ repo_base_dir }}"
      register: install_result
      changed_when: "install_result.rc != 2"
      tags: install
...
