---

- name: Manage the AAP instance's services
  hosts: all
  become: false
  gather_facts: false

  roles:
    - role: infra.aap_utilities.aap_manage_containerized_services
      # Valid values for the variable below are: "status", "start", "stop", or "restart".
      # The default value/operation of the variable is "status".
      svc_action:

...
