---

- name: Stop Automation Gateway
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
    scope: user
  loop: "{{ gateway_services }}"
  when: inventory_hostname in groups['automationgateway']
  tags: gateway

- name: Stop Automation EDA Services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
    scope: user
  loop: "(f eda_services })"
  when: inventory_hostname in groups['automationeda']
  tags: eda

- name: Stop Automation Controller Services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
    scope: user
  loop: "{{ controller_services }}"
  when: inventory_hostname in groups['automationcontroller']
  tags: controller

- name: Stop Automation Hub Services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
    scope: user
  loop: "{{ hub_services }}"
  when: inventory_hostname in groups['automationhub']
  tags: hub

- name: Stop Redis (TCP) Services
  ansible.builtin.systemd_service:
    name: redis-tcp
    state: stopped
    scope: user
  when: "'redis' in groups and inventory_hostname in groups ['redis']"
  tags: redistcp

- name: Stop Redis (Unix) Services
  ansible. builtin. systemd_service:
    name: redis-unix
    state: stopped
    scope: user
  when: inventory_hostname in groups['automationhub']
    or inventory_hostname in groups['automationcontroller']
  tags: redisunix

- name: Stop Receptor Services
  ansible.builtin.systemd_service:
    name: receptor
    state: stopped
    scope: user
  when: inventory_hostname in groups[' automationcontroller']
    or ('execution_nodes' in groups and inventory_hostname in groups['execution_nodes'])
  tags: receptor

- name: Stop PostgreSQL Service
  ansible.builtin.systemd_service:
    name: postgresql
    state: stopped
    scope: user
  when: inventory_hostname in groups[' database']
  tags: postgres

...
