---

- name: aap_start | Start PostgreSQL Service
  ansible.builtin.systemd_service:
    name: postgresql
    state: started
    scope: user
  when: inventory_hostname in groups['database']
  tags: postgres

- name: aap_start | Start Receptor Services
  ansible.builtin.systemd_service:
    name: receptor
    state: started
    scope: user
  when: inventory_hostname in groups['automationcontroller']
    or ('execution_nodes' in groups and inventory_hostname in groups['execution_nodes'])
  tags: receptor

- name: aap_start | Start Redis (Unix) Services
  ansible.builtin.systemd_service:
    name: redis-unix
    state: started
    scope: user
  when: inventory_hostname in groups['automationhub']
    or inventory_hostname in groups['automationcontroller']
  tags: redisunix

- name: aap_start | Start Redis (TCP) Services
  ansible.builtin.systemd_service:
    name: redis-tcp
    state: started
    scope: user
  when: "'redis' in groups and inventory_hostname in groups['redis']"
  tags: redistcp

- name: aap_start | Start Automation Hub Services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    scope: user
  loop: "{{ hub_services }}"
  when: inventory_hostname in groups['automationhub']
  tags: hub

- name: aap_start | Start Automation Controller Services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    scope: user
  loop: "{{ controller_services }}"
  when: inventory_hostname in groups['automationcontroller']
  tags: controller

- name: aap_start | Start Automation EDA Services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    scope: user
  loop: "{{ eda_services }}"
  when: inventory_hostname in groups['automationeda']
  tags: eda

- name: aap_start | Start Automation Gateway
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    scope: user
  loop: "{{ gateway_services }}"
  when: inventory_hostname in groups['automationgateway']
  tags: gateway

...
