---

# The value of svc_action is derived from the user-created playbook. The default value is "status".
- name: Include tasks for managing containerized AAP services
  ansible.builtin.include_tasks: aap__{{ svc_action }}.yml

...
