---
galaxy_info:
  author: Eric Lavarde
  description: Trigger installation of AAP given a prepared setup and inventory
  company: Red Hat

  license: GPL-3.0-or-later

  min_ansible_version: 2.14.0

  platforms:
    - name: Fedora
      versions:
        - all
        - "25"

  galaxy_tags: ['aap', 'ansible']

dependencies: []
...
