---
# tasks file for aap_setup_download
- name: Login to Red Hat APIs
  no_log: true
  ansible.builtin.uri:
    url: "{{ aap_setup_down_token_url }}"
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: refresh_token
      client_id: rhsm-api
      refresh_token: "{{ aap_setup_down_offline_token }}"
  register: __aap_setup_down_login

- name: Collecting the available installers
  no_log: true
  ansible.builtin.uri:
    url: "{{ aap_setup_down_images_url }}"
    method: GET
    return_content: true
    headers:
      Authorization: Bearer {{ __aap_setup_down_login.json.access_token }}
  register: __aap_setup_down_output

- name: Select the Specified installer to download
  ansible.builtin.set_fact:
    __aap_setup_down_images: "{{ __aap_setup_down_output.json.body | selectattr('filename', 'match', ((aap_setup_containerized | bool) | ternary('ansible-automation-platform-containerized-setup',
      'ansible-automation-platform-setup'))) | sort(attribute='datePublished', reverse=True) | selectattr('filename', 'search', (aap_setup_down_type | string) + '-'
      + (aap_setup_down_version | string)) }}"

- name: Display all the filenames available for download
  ansible.builtin.debug:
    msg: "{{ __aap_setup_down_images | map(attribute='filename') | list }}"

- name: Select the image to download or latest
  ansible.builtin.set_fact:
    is_aap_setup_down_latest: "{{ (__aap_image_to_download.filename == __aap_setup_down_images[0].filename) | bool }}"
    __aap_image_to_download: "{{ __aap_image_to_download }}"
    __aap_filtered_version_selected: "{{ __aap_filtered_version_selected }}"
  vars:
    __aap_filtered_version_selected: >-
      {{ __aap_setup_down_images | selectattr('filename', 'search', (aap_setup_down_version | string) + '-' + (aap_setup_down_version_patch | string)) | list }}
    __aap_image_to_download: >-
      {{ (__aap_filtered_version_selected | length > 0) | ternary(__aap_filtered_version_selected[0], __aap_setup_down_images[0]) }}

- name: Assert if a version is selected if its avail for download
  ansible.builtin.assert:
    that:
      - __aap_filtered_version_selected | length != 0
    fail_msg:
      - "The selected version {{ aap_setup_down_version }}-{{ aap_setup_down_version_patch }} is not available for download. Please check the version and try again."
      - "Available versions are: {{ __aap_setup_down_images | map(attribute='filename') | list }}"
  when: aap_setup_down_version_patch  # This is false when its not set.

- name: Notify if the selected version is not the latest
  ansible.builtin.pause:
    prompt: |
      ########################################################################################
      The selected version {{ __aap_image_to_download.filename }} is not the latest version
      The latest version is: {{ __aap_setup_down_images[0].filename }}
      A fact 'is_aap_setup_down_latest' is set to false.
      ########################################################################################
    seconds: 1
  when: not is_aap_setup_down_latest

- name: Downloading the installer of type {{ aap_setup_down_type }}
  no_log: true
  ansible.builtin.get_url:
    url: "{{ __aap_image_to_download.downloadHref }}"
    dest: "{{ aap_setup_down_dest_dir }}/{{ __aap_image_to_download.filename }}"
    mode: "0644"
    headers:
      Authorization: Bearer {{ __aap_setup_down_login.json.access_token }}
  register: __aap_setup_down_downloads

- name: Extract the name of the downloaded installer to aap_setup_down_installer_file
  ansible.builtin.set_fact:
    aap_setup_down_installer_file: "{{ __aap_setup_down_downloads.dest }}"

- name: Set aap_setup_down_version fact
  ansible.builtin.set_fact:
    aap_setup_down_version: "{{ aap_setup_down_version }}"
...
