---
name: Ansible sanity

on:
  push:
    branches: [devel]
  pull_request:

permissions:
  contents: read

jobs:
  sanity:
    uses: ansible/ansible-content-actions/.github/workflows/sanity.yaml@05894f1a7922836072b5a12e80f9c2ed5f489567 # main
