---
name: Ansible sanity

on:
  push:
    branches: [devel]
  pull_request:

permissions:
  contents: read

jobs:
  sanity:
    uses: ansible/ansible-content-actions/.github/workflows/sanity.yaml@2f18fdf5765dfdcd31781acb9c9b3206bc3f34ea # main
