---
name: Ansible sanity

on:
  push:
    branches: [devel]
  pull_request:

permissions:
  contents: read

jobs:
  sanity:
    uses: ansible/ansible-content-actions/.github/workflows/sanity.yaml@c81d405f1de6452c2ba7ddaca919afc65f8fe7ca # main
